[theme]
primaryColor = "#F18F01"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 100
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
